-- MySQL Script generated by MySQL Workbench
-- Dom 08 Out 2017 18:49:17 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaFisica` (
  `Pessoa_idPessoa` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `RG` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `dataNascimento` VARCHAR(15) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  INDEX `fk_PessoaFisica_Pessoa_idx_idx` (`Pessoa_idPessoa` ASC),
  PRIMARY KEY (`CPF`),
  CONSTRAINT `fk_PessoaFisica_Pessoa_idx`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agricultor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agricultor` (
  `idAgricultor` INT NOT NULL,
  `cadPro` VARCHAR(45) NOT NULL,
  `PessoaFisica_CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAgricultor`),
  UNIQUE INDEX `PessoaFisica_CPF_UNIQUE` USING BTREE (`PessoaFisica_CPF` ASC),
  CONSTRAINT `fk_Agricultor_PessoaFisica`
    FOREIGN KEY (`PessoaFisica_CPF`)
    REFERENCES `mydb`.`PessoaFisica` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Insumo` (
  `idInsumo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `especificacoes` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `dataValidade` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInsumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Regiao` (
  `idRegiao` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRegiao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plantacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plantacao` (
  `idPlantacao` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `regiao` INT NOT NULL,
  PRIMARY KEY (`idPlantacao`),
  INDEX `fk_Plantacao_Regiao_idx` (`regiao` ASC),
  CONSTRAINT `fk_Plantacao_Regiao`
    FOREIGN KEY (`regiao`)
    REFERENCES `mydb`.`Regiao` (`idRegiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
